CREATE TABLE "CRAWLER_LIGHTINDUSTRYPAPER" (
"ID" NUMBER(18) NOT NULL ,
"INDUSTRYNAME" VARCHAR2(200 BYTE) NULL ,
"GUID" VARCHAR2(100 BYTE) NULL ,
"DATAITEM" VARCHAR2(200 BYTE) NULL ,
"DATATYPE" VARCHAR2(100 BYTE) NULL ,
"MODIFYFREQUENCY" VARCHAR2(200 BYTE) NULL ,
"UNIT" VARCHAR2(50 BYTE) NULL ,
"DATAINTERFACE" VARCHAR2(100 BYTE) NULL ,
"ISVALID" NUMBER(1) DEFAULT 1  NULL ,
"ENTRYTIME" DATE DEFAULT sysdate  NULL ,
"UPDATETIME" DATE DEFAULT sysdate  NULL ,
"GROUNDTIME" DATE DEFAULT sysdate  NULL ,
"UPDATEID" NUMBER(18) DEFAULT 1  NULL ,
"RESOURCEID" VARCHAR2(20 BYTE) NULL ,
"RECORDID" VARCHAR2(50 BYTE) NULL 
)
LOGGING
NOCOMPRESS
NOCACHE
;
COMMENT ON TABLE "CRAWLER_LIGHTINDUSTRYPAPER" IS '轻工业-纸基础表';
COMMENT ON COLUMN "CRAWLER_LIGHTINDUSTRYPAPER"."ID" IS '流水号';
COMMENT ON COLUMN "CRAWLER_LIGHTINDUSTRYPAPER"."INDUSTRYNAME" IS '行业';
COMMENT ON COLUMN "CRAWLER_LIGHTINDUSTRYPAPER"."GUID" IS '数据拉取GUID';
COMMENT ON COLUMN "CRAWLER_LIGHTINDUSTRYPAPER"."DATAITEM" IS '数据项名称';
COMMENT ON COLUMN "CRAWLER_LIGHTINDUSTRYPAPER"."DATATYPE" IS '数据类型';
COMMENT ON COLUMN "CRAWLER_LIGHTINDUSTRYPAPER"."MODIFYFREQUENCY" IS '需求数据周期';
COMMENT ON COLUMN "CRAWLER_LIGHTINDUSTRYPAPER"."UNIT" IS '单位（根据实际情况，可空）';
COMMENT ON COLUMN "CRAWLER_LIGHTINDUSTRYPAPER"."DATAINTERFACE" IS '数据拉取接口';
COMMENT ON COLUMN "CRAWLER_LIGHTINDUSTRYPAPER"."ISVALID" IS '是否有效 0-否;1-是';
COMMENT ON COLUMN "CRAWLER_LIGHTINDUSTRYPAPER"."ENTRYTIME" IS '记录进表时间';
COMMENT ON COLUMN "CRAWLER_LIGHTINDUSTRYPAPER"."UPDATETIME" IS '记录修改时间';
COMMENT ON COLUMN "CRAWLER_LIGHTINDUSTRYPAPER"."GROUNDTIME" IS '记录落地时间';
COMMENT ON COLUMN "CRAWLER_LIGHTINDUSTRYPAPER"."UPDATEID" IS '变动标识';
COMMENT ON COLUMN "CRAWLER_LIGHTINDUSTRYPAPER"."RESOURCEID" IS '来源标识';
COMMENT ON COLUMN "CRAWLER_LIGHTINDUSTRYPAPER"."RECORDID" IS '来源记录';
ALTER TABLE "CRAWLER_LIGHTINDUSTRYPAPER" ADD PRIMARY KEY ("ID");
